IMPORTING NECESSARY LIBRARIES

In [8]:
import numpy as np
import pandas as pd

EXTRACTION LAYER

In [16]:
global_df = pd.read_csv(r'C:\Users\Windows 10\Downloads\globex_retail\globex_retail\dataset\rawdata\globex_retail_data - globex_retail_data.csv')

In [19]:
global_df.head(30)

,Customer_ID,Order_ID,Order_Date,Product_Category,Product_Sub_Category,Quantity,Price,Discount,Customer_Location,Revenue
0,CUST_013738,ORD_00102406,1/1/2023,Home & Garden,Gardening Tools,1,419.19,0.00,TN,419.1900
1,CUST_011726,ORD_00102902,1/1/2023,Electronics,Laptops,1,222.37,0.09,TN,202.3567
2,CUST_010891,ORD_00103864,1/1/2023,Electronics,Laptops,6,1107.65,0.00,IN,6645.9000
3,CUST_011452,ORD_00103560,1/1/2023,Electronics,Gaming Consoles,5,288.84,0.00,MA,1444.2000
4,CUST_010886,ORD_00100632,1/2/2023,Electronics,Headphones,1,191.27,0.00,AZ,191.2700
5,CUST_010410,ORD_00103733,1/2/2023,Clothing,Shoes,4,200.47,0.37,MI,505.1844
6,CUST_011600,ORD_00103814,1/2/2023,Beauty,Personal Care,5,115.09,0.08,MI,529.4140
7,CUST_012368,ORD_00104082,1/2/2023,Clothing,Shoes,1,118.51,0.00,IN,118.5100
8,CUST_014778,ORD_00102022,1/2/2023,Books,Non-Fiction,2,30.23,0.00,TX,60.4600
9,CUST_010262,ORD_00104782,1/2/2023,Home & Garden,Furniture,1,285.41,0.00,LA,285.4100
10,CUST_011456,ORD_00100626,1/2/2023,Beauty,Personal Care,1,27.53,0.00,LA,27.5300
11,CUST_011615,ORD_00103622,1/3/2023,Beauty,Skincare,1,16.59,0.00,KY,16.5900
12,CUST_014005,ORD_00101482,1/3/2023,Electronics,Smart Watches,4,1417.28,0.00,OK,5669.1200
13,CUST_013862,ORD_00103766,1/3/2023,Sports,Water Sports,1,262.59,0.27,MD,191.6907
14,CUST_014608,ORD_00103883,1/4/2023,Sports,Winter Sports,1,204.56,0.00,MN,204.5600
15,CUST_013835,ORD_00103674,1/4/2023,Electronics,Tablets,3,1884.25,0.41,TX,3335.1225
16,CUST_010934,ORD_00104963,1/4/2023,Home & Garden,Bedding,2,799.61,0.29,CO,1135.4462
17,CUST_013629,ORD_00104506,1/4/2023,Clothing,Accessories,1,29.90,0.00,GA,29.9000
18,CUST_011705,ORD_00104918,1/5/2023,Clothing,Mens Shirts,5,84.81,0.00,IN,424.0500
19,CUST_010104,ORD_00102567,1/5/2023,Home & Garden,Gardening Tools,7,314.05,0.00,KY,2198.3500
20,CUST_014197,ORD_00104812,1/5/2023,Electronics,Tablets,1,694.07,0.00,SC,694.0700
21,CUST_011361,ORD_00104720,1/5/2023,Electronics,Tablets,1,253.74,0.00,AZ,253.7400
22,CUST_013358,ORD_00103988,1/5/2023,Home & Garden,Kitchen Appliances,5,610.83,0.00,IN,3054.1500
23,CUST_011079,ORD_00104397,1/5/2023,Electronics,Headphones,2,836.92,0.00,GA,1673.8400
24,CUST_014710,ORD_00100866,1/5/2023,Home & Garden,Kitchen Appliances,2,352.35,0.00,NY,704.7000
25,CUST_013508,ORD_00104696,1/6/2023,Clothing,Jeans,1,222.19,0.00,AZ,222.1900
26,CUST_012294,ORD_00103525,1/6/2023,Electronics,Smartphones,4,1078.15,0.00,CO,4312.6000
27,CUST_013331,ORD_00102230,1/6/2023,Home & Garden,Storage,2,425.30,0.00,MO,850.6000
28,CUST_013066,ORD_00102305,1/6/2023,Books,Non-Fiction,1,11.25,0.00,TN,11.2500
29,CUST_010750,ORD_00100470,1/6/2023,Home & Garden,Gardening Tools,1,452.26,0.00,NC,452.2600

VIEWING THE STRUCTURE OF THE DATA

In [20]:
global_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           5000 non-null   object
 1   Order_ID              5000 non-null   object
 2   Order_Date            5000 non-null   object
 3   Product_Category      5000 non-null   object
 4   Product_Sub_Category  5000 non-null   object
 5   Quantity              5000 non-null   int64
 6   Price                 5000 non-null   float64
 7   Discount              5000 non-null   float64
 8   Customer_Location     5000 non-null   object
 9   Revenue               5000 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 390.8+ KB

In [21]:
global_df.columns

Index(['Customer_ID', 'Order_ID', 'Order_Date', 'Product_Category',
       'Product_Sub_Category', 'Quantity', 'Price', 'Discount',
       'Customer_Location', 'Revenue'],
      dtype='object')

DATA CLEANING AND TRANSFORMATION

In [23]:
### ### There is no mssing value as the number of rows are same but the order_date is supposed to bein datetime data type 
# not string object, thus we will convert the data type of Order_Date to datetime.

global_df['Order_Date'] = pd.to_datetime(global_df['Order_Date'])

In [24]:
global_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           5000 non-null   object
 1   Order_ID              5000 non-null   object
 2   Order_Date            5000 non-null   datetime64[ns]
 3   Product_Category      5000 non-null   object
 4   Product_Sub_Category  5000 non-null   object
 5   Quantity              5000 non-null   int64
 6   Price                 5000 non-null   float64
 7   Discount              5000 non-null   float64
 8   Customer_Location     5000 non-null   object
 9   Revenue               5000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 390.8+ KB

DATA MODELLING / NORMALZATION

In [25]:
##We will first build tables with primary keys then build tables with foreign keys.

#Customer Table

customer_df = global_df[['Customer_ID', 'Customer_Location']].copy().drop_duplicates().reset_index(drop=True)
customer_df.head(30)

    Customer_ID Customer_Location
0   CUST_013738                TN
1   CUST_011726                TN
2   CUST_010891                IN
3   CUST_011452                MA
4   CUST_010886                AZ
5   CUST_010410                MI
6   CUST_011600                MI
7   CUST_012368                IN
8   CUST_014778                TX
9   CUST_010262                LA
10  CUST_011456                LA
11  CUST_011615                KY
12  CUST_014005                OK
13  CUST_013862                MD
14  CUST_014608                MN
15  CUST_013835                TX
16  CUST_010934                CO
17  CUST_013629                GA
18  CUST_011705                IN
19  CUST_010104                KY
20  CUST_014197                SC
21  CUST_011361                AZ
22  CUST_013358                IN
23  CUST_011079                GA
24  CUST_014710                NY
25  CUST_013508                AZ
26  CUST_012294                CO
27  CUST_013331                MO
28  CUST_013066                TN
29  CUST_010750                NC

In [32]:
#Product Table

product_df = global_df[['Product_Category', 'Product_Sub_Category', 'Price', 'Discount']].copy().drop_duplicates().reset_index(drop=True)

product_df.head(30)

   Product_Category Product_Sub_Category    Price  Discount
0     Home & Garden      Gardening Tools   419.19      0.00
1       Electronics              Laptops   222.37      0.09
2       Electronics              Laptops  1107.65      0.00
3       Electronics      Gaming Consoles   288.84      0.00
4       Electronics           Headphones   191.27      0.00
5          Clothing                Shoes   200.47      0.37
6            Beauty        Personal Care   115.09      0.08
7          Clothing                Shoes   118.51      0.00
8             Books          Non-Fiction    30.23      0.00
9     Home & Garden            Furniture   285.41      0.00
10           Beauty        Personal Care    27.53      0.00
11           Beauty             Skincare    16.59      0.00
12      Electronics        Smart Watches  1417.28      0.00
13           Sports         Water Sports   262.59      0.27
14           Sports        Winter Sports   204.56      0.00
15      Electronics              Tablets  1884.25      0.41
16    Home & Garden              Bedding   799.61      0.29
17         Clothing          Accessories    29.90      0.00
18         Clothing          Mens Shirts    84.81      0.00
19    Home & Garden      Gardening Tools   314.05      0.00
20      Electronics              Tablets   694.07      0.00
21      Electronics              Tablets   253.74      0.00
22    Home & Garden   Kitchen Appliances   610.83      0.00
23      Electronics           Headphones   836.92      0.00
24    Home & Garden   Kitchen Appliances   352.35      0.00
25         Clothing                Jeans   222.19      0.00
26      Electronics          Smartphones  1078.15      0.00
27    Home & Garden              Storage   425.30      0.00
28            Books          Non-Fiction    11.25      0.00
29    Home & Garden      Gardening Tools   452.26      0.00

In [31]:
#Order Table
Order_df = global_df[['Order_ID', 'Customer_ID', 'Product_Category', 'Order_Date', 'Quantity', 'Revenue']].copy().drop_duplicates().reset_index(drop=True)
Order_df.head(30)

        Order_ID  Customer_ID Product_Category Order_Date  Quantity    Revenue
0   ORD_00102406  CUST_013738    Home & Garden 2023-01-01         1   419.1900
1   ORD_00102902  CUST_011726      Electronics 2023-01-01         1   202.3567
2   ORD_00103864  CUST_010891      Electronics 2023-01-01         6  6645.9000
3   ORD_00103560  CUST_011452      Electronics 2023-01-01         5  1444.2000
4   ORD_00100632  CUST_010886      Electronics 2023-01-02         1   191.2700
5   ORD_00103733  CUST_010410         Clothing 2023-01-02         4   505.1844
6   ORD_00103814  CUST_011600           Beauty 2023-01-02         5   529.4140
7   ORD_00104082  CUST_012368         Clothing 2023-01-02         1   118.5100
8   ORD_00102022  CUST_014778            Books 2023-01-02         2    60.4600
9   ORD_00104782  CUST_010262    Home & Garden 2023-01-02         1   285.4100
10  ORD_00100626  CUST_011456           Beauty 2023-01-02         1    27.5300
11  ORD_00103622  CUST_011615           Beauty 2023-01-03         1    16.5900
12  ORD_00101482  CUST_014005      Electronics 2023-01-03         4  5669.1200
13  ORD_00103766  CUST_013862           Sports 2023-01-03         1   191.6907
14  ORD_00103883  CUST_014608           Sports 2023-01-04         1   204.5600
15  ORD_00103674  CUST_013835      Electronics 2023-01-04         3  3335.1225
16  ORD_00104963  CUST_010934    Home & Garden 2023-01-04         2  1135.4462
17  ORD_00104506  CUST_013629         Clothing 2023-01-04         1    29.9000
18  ORD_00104918  CUST_011705         Clothing 2023-01-05         5   424.0500
19  ORD_00102567  CUST_010104    Home & Garden 2023-01-05         7  2198.3500
20  ORD_00104812  CUST_014197      Electronics 2023-01-05         1   694.0700
21  ORD_00104720  CUST_011361      Electronics 2023-01-05         1   253.7400
22  ORD_00103988  CUST_013358    Home & Garden 2023-01-05         5  3054.1500
23  ORD_00104397  CUST_011079      Electronics 2023-01-05         2  1673.8400
24  ORD_00100866  CUST_014710    Home & Garden 2023-01-05         2   704.7000
25  ORD_00104696  CUST_013508         Clothing 2023-01-06         1   222.1900
26  ORD_00103525  CUST_012294      Electronics 2023-01-06         4  4312.6000
27  ORD_00102230  CUST_013331    Home & Garden 2023-01-06         2   850.6000
28  ORD_00102305  CUST_013066            Books 2023-01-06         1    11.2500
29  ORD_00100470  CUST_010750    Home & Garden 2023-01-06         1   452.2600

In [33]:
#Save the tables as csv files

customer_df.to_csv(r'dataset\cleaneddata\customer_table.csv', index=False)
Order_df.to_csv(r'dataset\cleaneddata\order_table.csv', index=False)
product_df.to_csv(r'dataset\cleaneddata\product_table.csv', index=False)